<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>打印机连接生成器</AssemblyName>
        <RootNamespace>PrinterConnectTool.Generator</RootNamespace>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>printerone.ico</ApplicationIcon>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.1" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\ScriptTemplate.ps1" LogicalName="PrinterConnectTool.Generator.Resources.ScriptTemplate.ps1" />
        <EmbeddedResource Include="Resources\Shell.exe" LogicalName="PrinterConnectTool.Generator.Resources.Shell.exe" />
    </ItemGroup>

</Project>
